# Generated by Django 5.0.1 on 2024-01-08 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=64)),
                ('lastName', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=64)),
                ('tel', models.CharField(blank=True, max_length=64)),
                ('bgIconColor', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('kanban', models.CharField(blank=True, max_length=64)),
                ('priority', models.CharField(blank=True, max_length=64)),
                ('subtasksstatus', models.JSONField(blank=True, max_length=1024)),
                ('subtasks', models.JSONField(blank=True, max_length=1024)),
                ('assigned', models.ManyToManyField(blank=True, related_name='assignees', to='tasks.contact')),
            ],
        ),
    ]
