# Generated by Django 5.0.1 on 2024-01-03 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='descrption',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='task',
            name='kanban',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasksstatus',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
