# Generated by Django 5.0.1 on 2024-01-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_task_category_task_descrption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrption',
            new_name='description',
        ),
    ]
