# Generated by Django 5.0.1 on 2024-01-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='assignees', to='tasks.contact'),
        ),
    ]
