# Generated by Django 5.0.1 on 2024-01-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subtasksstatus',
            new_name='subtaskStatus',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ManyToManyField(blank=True, related_name='assignees', to='tasks.contact'),
        ),
    ]
